Module6-task1
htmlacademy-ecmascript/270653-big-trip-15 pull request #10
Opened 2021-08-21 09:59 UTC by MikhailinNik

2021-09-01 20:21 UTC, AlexMasterov requested changes

2021-09-01 20:21 UTC, AlexMasterov commented on src/utils/const.js
>  const InputValueForSort = {
```diff
- const InputValueForSort = {
+ const SortType = {
```

2021-09-01 20:21 UTC, AlexMasterov commented on src/view/form-edit.js
> +  const renderOffers = getOffers(offers, pointTypeToOffers[data.type] || []);
<details>
<summary>view/form-edit.js</summary>

https://github.com/htmlacademy-ecmascript/270653-big-trip-15/blob/dda856066e52181f938f9d6fb44dcd453b432f4d/src/view/form-edit.js#L121
https://github.com/htmlacademy-ecmascript/270653-big-trip-15/blob/dda856066e52181f938f9d6fb44dcd453b432f4d/src/view/form-edit.js#L8
https://github.com/htmlacademy-ecmascript/270653-big-trip-15/blob/dda856066e52181f938f9d6fb44dcd453b432f4d/src/view/form-edit.js#L22
</details>

```js
pointTypeToOffers // undefined
```

Нужно в функцию шаблона вторым аргументом передать объект-словарь `pointTypeToOffers`.

2021-09-01 20:21 UTC, AlexMasterov commented on src/view/form-edit.js
> +  // const renderOffers = getOffers(offers, typeOffers);
`//`

Нужно удалить.

Б18

2021-09-01 20:21 UTC, AlexMasterov commented on src/view/form-edit.js
> +        ${isEdit
<details>
<summary>view/form-edit.js</summary>

https://github.com/htmlacademy-ecmascript/270653-big-trip-15/blob/dda856066e52181f938f9d6fb44dcd453b432f4d/src/view/form-edit.js#L75-L82
</details>

Нужно в этом месте исправить ошибки линтера.

Б15

2021-09-01 20:21 UTC, AlexMasterov commented on src/view/form-edit.js
> +export default class FormEdit extends SmartView {
<details>
<summary>FormEdit</summary>

https://github.com/htmlacademy-ecmascript/270653-big-trip-15/blob/dda856066e52181f938f9d6fb44dcd453b432f4d/src/view/form-edit.js#L138
https://github.com/htmlacademy-ecmascript/270653-big-trip-15/blob/dda856066e52181f938f9d6fb44dcd453b432f4d/src/view/form-edit.js#L154
https://github.com/htmlacademy-ecmascript/270653-big-trip-15/blob/dda856066e52181f938f9d6fb44dcd453b432f4d/src/view/form-edit.js#L162
</details>

[`Д 8`](https://up.htmlacademy.ru/ecmascript/15/criteries#d8)
> Методы внутри классов упорядочены

3. Основные методы класса
4. **Обработчики событий**

2021-09-01 20:21 UTC, AlexMasterov commented on src/view/form-edit.js
> +      .addEventListener('click', this._onRollUpButtonClick);
Уже писал, что это одно слово:
```diff
- .addEventListener('click', this._onRollUpButtonClick);
+ .addEventListener('click', this._onRollupButtonClick);
```

2021-09-01 20:21 UTC, AlexMasterov commented on src/view/form-edit.js
> +  _setInnerHandlers() {
<details>
<summary>_setInnerHandlers</summary>

https://github.com/htmlacademy-ecmascript/270653-big-trip-15/blob/dda856066e52181f938f9d6fb44dcd453b432f4d/src/view/form-edit.js#L176
https://github.com/htmlacademy-ecmascript/270653-big-trip-15/blob/dda856066e52181f938f9d6fb44dcd453b432f4d/src/view/form-edit.js#L180
</details>

**2x** this.`getElement()`

2021-09-01 20:21 UTC, AlexMasterov commented on src/view/form-edit.js
> +      .addEventListener('change', this._onEventTypeChange);
.event__`type-group` + `change` !== this._on`EventType`Change

Д4

2021-09-01 20:21 UTC, AlexMasterov commented on src/view/smart.js
> +  updateData(update, justDataUpdating) {
Желательно определиться и задать значение по умолчанию, например:
```diff
- updateData(update, justDataUpdating) {
+ updateData(update, justDataUpdating = true) {
```

2021-09-01 20:21 UTC, AlexMasterov commented on src/view/smart.js
> +  updateElement() {
<details>
<summary>updateElement</summary>

https://github.com/htmlacademy-ecmascript/270653-big-trip-15/blob/dda856066e52181f938f9d6fb44dcd453b432f4d/src/view/smart.js#L28
https://github.com/htmlacademy-ecmascript/270653-big-trip-15/blob/dda856066e52181f938f9d6fb44dcd453b432f4d/src/view/smart.js#L32
</details>

prev`Element`
new`Element`

В нашем случае нужно убрать из названия переменных `Element` (переименовать).

Д6

2021-09-01 20:21 UTC, AlexMasterov commented on src/view/sort.js
<details>
<summary>view/sort.js</summary>

https://github.com/htmlacademy-ecmascript/270653-big-trip-15/blob/dda856066e52181f938f9d6fb44dcd453b432f4d/src/view/sort.js#L32
https://github.com/htmlacademy-ecmascript/270653-big-trip-15/blob/dda856066e52181f938f9d6fb44dcd453b432f4d/src/view/sort.js#L48
</details>

`Sort`._onTrip`Sort`Click

[`Д 3`](https://up.htmlacademy.ru/ecmascript/15/criteries#d3)
> Название методов и свойств объектов не содержит [полное] название объектов

2021-09-01 20:27 UTC, AlexMasterov requested changes

2021-09-01 20:27 UTC, AlexMasterov commented on src/view/form-edit.js
> +export const createPointFormTemplate = (data, pointTypeToOffers = {}) => {
<details>
<summary>Проблема</summary>

![image](https://user-images.githubusercontent.com/700213/131740031-94091110-a23e-4829-be9c-82b48937af6c.png)

</details>

Сейчас можно задать отрицательную стоимость.

См. ТЗ:
> Стоимость. **Целое положительное _число_**

2021-09-01 20:37 UTC, AlexMasterov requested changes

2021-09-01 20:37 UTC, AlexMasterov commented on src/utils/const.js
<details>
<summary>Проблема</summary>

![image](https://user-images.githubusercontent.com/700213/131741057-1de5112d-b40b-4b0b-bccf-a5e24fbf0856.png)

</details>

При попытке добавить точку маршрута в избранное кнопка не меняет состояние.

См. ТЗ:
> Кнопка «Favorite» (отображается в виде звёздочки). Добавляет точку маршрута в избранное. **После добавления в избранное, кнопка меняет состояние — яркая звезда**. Повторный клик по кнопке удаляет точку маршрута из избранного и возвращает кнопку в исходное состояние

Нужно исправить.

2021-09-01 20:43 UTC, AlexMasterov requested changes

2021-09-01 20:43 UTC, AlexMasterov commented on src/utils/const.js
<details>
<summary>Проблема</summary>

![image](https://user-images.githubusercontent.com/700213/131741623-f57b0dd4-043e-491a-b04d-05458dc0c413.png)

</details>

Сейчас при смене типа список предложений не изменяется.

См. ТЗ:
> Дополнительные опции. **В зависимости от типа точки маршрута пользователь может выбрать дополнительные опции (`offers`)** 

Нужно в тест. данных `allOffers` добавить еще один _тип_ и доработать этот пункт ТЗ.

2021-09-01 20:43 UTC, AlexMasterov commented on src/view/form-edit.js
> +        <option value="${destination.name}"></option>
<details>
<summary>Проблема</summary>

![image](https://user-images.githubusercontent.com/700213/131741880-207f9926-7c21-43c1-9089-b9d8c75c808c.png)

</details>

В этом месте всё также на основе _общего_ списка `destinations` нужно создавать разметку с `<option>`.

Нужно исправить (вернуть, как было).

> Для этого нужно в функцию создании шаблона неким образом снова передать общий список `destinations` и использовать его для создании `<option>`

2021-09-04 17:38 UTC, MikhailinNik commented on src/utils/const.js
Саш, я не совсем понял, в чём у меня проблема, помоги пожалуйста

2021-09-04 17:40 UTC, MikhailinNik commented on src/view/form-edit.js
> +        <option value="${destination.name}"></option>
Я вроде сделал как было, но всё равно у меня пункт назначения меняется обратно на Moscow, объясни пожалуйста в чём у меня проблема

2021-09-04 18:03 UTC, AlexMasterov commented on src/utils/const.js
> Саш, я не совсем понял, в чём у меня проблема, помоги пожалуйста

Насколько помню, сначала при нажатии на кнопку "Звездочка", которая добавляет в избранное, кнопка не становилась желтой и данные с точкой маршрута не изменялись (= `point.isFavorite = true`).

Сейчас же при нажатии ошибка:

<details>
<summary>Ошибка</summary>

```
Uncaught TypeError: Cannot read properties of undefined (reading 'map')
    at createPointFormTemplate (form-edit.js:51)
    at FormEdit.getTemplate (form-edit.js:117)
    at FormEdit.getElement (abstract.js:19)
    at FormEdit._setInnerHandlers (form-edit.js:147)
    at new FormEdit (form-edit.js:113)
    at Waypoint.init (waypoint.js:33)
    at PointList._changeData (point-list.js:71)
    at Waypoint._handleFavouriteClick (waypoint.js:98)
    at Waypoint._onFavouriteButtonClick (waypoint.js:73)
```
</details>

При нажатие на кнопку со звездочкой нужно изменять данные точки маршрута и добавлять в разметку с кнопкой спец. класс: `event__favorite-btn--active`.

Пож. уточни, был непонятен этот пункт ТЗ или не получилось реализовать?

2021-09-04 18:10 UTC, AlexMasterov commented on src/view/form-edit.js
> +        <option value="${destination.name}"></option>
> Я вроде сделал как было, но всё равно у меня пункт назначения меняется обратно на Moscow, объясни пожалуйста в чём у меня проблема

Это стандартное поведение, а замечание касалась только создание `<option>` на основе массива с названиями направлений.

2021-09-04 18:10 UTC, MikhailinNik commented on src/utils/const.js
я думал, надо было добавлять спец.класс` event__favorite-btn--${isFavourite}`, т.е. isFavourite=true, а теперь isFavourite должен быть флагом как я понял?

2021-09-04 18:14 UTC, AlexMasterov commented on src/view/form-edit.js
> +export default class FormEdit extends SmartView {
<details>
<summary>Проблема</summary>

```
form-edit.js:51 Uncaught TypeError: Cannot read properties of undefined (reading 'map')
    at createPointFormTemplate (form-edit.js:51)
```
</details>

При сохранении данных через форму (или нажатие на кнопку "Звездочка") появляется ошибка.

Нужно разобраться при выполнении следующего задания.

2021-09-04 18:15 UTC, AlexMasterov commented on src/utils/const.js
Если `point.isFavourite = true`, то в разметку кнопки _добавляется_ класс `event__favorite-btn--active`.

Если `point.isFavourite = true`, то ничего не добавляется 😃

2021-09-04 18:16 UTC, AlexMasterov commented on src/view/form-edit.js
> +      .addEventListener('click', this._onRollUpButtonClick);
На всякий случай напомню про это замечание: `Rollup` и `RollUp` разные слова 😃

2021-09-04 18:17 UTC, merged

2021-09-04 18:20 UTC, AlexMasterov commented on src/view/sort.js
> +  _onTripClick(evt) {
Уж лучше так:
```diff
- _onTripClick(evt) {
+ _onClick(evt) {
```