Добавлена библиотека flatpickr для установки даты в форме редактирования
htmlacademy-ecmascript/270653-big-trip-15 pull request #11
Opened 2021-09-05 16:50 UTC by MikhailinNik

2021-09-05 16:52 UTC, MikhailinNik commented
фывфыв

2021-09-05 16:54 UTC, MikhailinNik commented
Саш, у меня возникает ошибка при установке даты с помощью flatpickr, пишет, что дата невалидная и значение даты(либо начало или конец = null), объясни пожалуйста, где я накосячил?

2021-09-05 18:30 UTC, AlexMasterov requested changes

2021-09-05 18:30 UTC, AlexMasterov commented on src/view/form-edit.js
> +import '../../node_modules/flatpickr/dist/flatpickr.min.css';
🤔

Webpack разберется:
```diff
- import '../../node_modules/flatpickr/dist/flatpickr.min.css';
+ import 'flatpickr/dist/flatpickr.min.css';
```

2021-09-05 18:30 UTC, AlexMasterov commented on src/view/form-edit.js
> +export const createPointFormTemplate = (data, pointTypeToOffers = [], destinations = []) => {
export const createPointFormTemplate = (data, `pointTypeToOffers` = `[]`, destinations = []) => {

См. снова https://github.com/htmlacademy-ecmascript/270653-big-trip-15/pull/8#discussion_r690873565.

2021-09-05 18:30 UTC, AlexMasterov commented on src/view/form-edit.js
> +import { createFormatForDate } from '@utils/util';
import { `create`FormatForDate } from '@utils/util';

Функция форматирует, а не создает функции-форматеры дат. 
Иначе говоря: она не _фабрика_ и поэтому не должна называться `createFormat`.

> Подобное именование вводит в заблуждение

import { createFormat`For`Date } from '@utils/util';

Снова избыточный для именования `For`.

2021-09-05 18:30 UTC, AlexMasterov commented on src/view/form-edit.js
> +          ${destinations.map(({ name }) => `<option value="${name}">${name}</option>`).join(' ')}
.join(`' '`)}

Без причины увеличил размер страницы для передачи пользователю.

2021-09-05 18:30 UTC, AlexMasterov commented on src/view/form-edit.js
> +    if(this._flatpickerDateFrom) {
<details>
<summary>view/form-edit.js</summary>

https://github.com/htmlacademy-ecmascript/270653-big-trip-15/blob/32b1278ca66e98348b539c146f0731689d9d7ce6/src/view/form-edit.js#L118-L119
</details>

Неявная проверка, который требует приведения типов.

```diff
- if(this._flatpickerDateFrom) {
+ if (this._flatpickerDateFrom !== null) {
```

2021-09-05 18:30 UTC, AlexMasterov commented on src/view/form-edit.js
> +    this._setDateTopicker();
this._setDateFrom`picker`();
this._setDateTo`picker`();

[`Б 3`](https://up.htmlacademy.ru/ecmascript/15/criteries#b3)
> Название переменных, параметров, свойств и методов начинается со строчной буквы и записываются в нотации `camelCase`

2021-09-05 18:30 UTC, AlexMasterov commented on src/view/form-edit.js
>    _onRollUpButtonClick(evt) {
_on`RollUp`ButtonClick(evt) {

[`Б 4`](https://up.htmlacademy.ru/ecmascript/15/criteries#b4)
> Для названия значений используются английские существительные

```diff
- _onRollUpButtonClick(evt) {
+ _onRollupButtonClick(evt) {
```

2021-09-05 18:30 UTC, AlexMasterov commented on src/view/form-edit.js
> +    const destination = this._destinations.find((obj) => obj.name === name);
this._destinations.find((`obj`) => `obj`.name === name);

[`Б 4`](https://up.htmlacademy.ru/ecmascript/15/criteries#b4)
> Сокращения в словах запрещены

```js
typeof obj // object
```

[`Б 9`](https://up.htmlacademy.ru/ecmascript/15/criteries#b9)
> В названии переменных не используется тип данных (= `object`)

2021-09-05 18:30 UTC, AlexMasterov commented on src/view/form-edit.js
> +    }), false;
}), `false`;

`false` за пределами аргументов функций.

2021-09-05 18:30 UTC, AlexMasterov commented on src/view/form-edit.js
> +      dateFrom: this._flatpickerDateFrom.set('minDate', userDate),
> Саш, у меня возникает ошибка при установке даты с помощью flatpickr, пишет, что дата невалидная и значение даты(либо начало или конец = null), объясни пожалуйста, где я накосячил?

` dateFrom`: this._flatpickerDateFrom.`set`('minDate', userDate)

Метод `.set`, как подсказывает название, ничего не возвращает, т.е. ` dateFrom` = `undefined`.

Попробуй так:
```js
this._flatpickerDateFrom.set('minDate', userDate);
this.updateData({
  dateFrom: userDate,
// ...
```
> Нужно также исправить в другом обработчике

2021-09-05 18:30 UTC, AlexMasterov commented on src/view/form-edit.js
> +    }, false);
Сейчас выбор даты не влияет на другие места формы.

Поэтому не нужно её перерисовывать:
```diff
- }, false);
+ }, true);
```
> Нужно также учесть в другом обработчике

2021-09-05 18:30 UTC, AlexMasterov commented on src/view/form-edit.js
<details>
<summary>Проблема</summary>

![image](https://user-images.githubusercontent.com/700213/132137504-913f0805-6ee6-4bb9-8076-8fc68ee596d0.png)

</details>

При сохранение формы в DOM накапливаются объекты `flatpicker`, включая его обработчиков.

[`Б 36`](https://up.htmlacademy.ru/ecmascript/15/criteries#b36)
> Обработчики события добавляются и удаляются своевременно

> См. (частичное) решение этой проблемы в демо проекте

2021-09-06 20:09 UTC, MikhailinNik commented
Я так и не понял, почему не удаляются DOM элементы и обработчики flatpickr, я что то упустил наверное, но что, не могу понять, подскажи пожалуйста

2021-09-06 20:17 UTC, AlexMasterov commented
> Я так и не понял, почему не удаляются DOM элементы и обработчики flatpickr, я что то упустил наверное, но что, не могу понять, подскажи пожалуйста

При сохранении или закрытии формы из DOM удаляется элемент компонента формы, а на уровне JS с помощью метода [Abstract.`removeElement`](https://github.com/htmlacademy-ecmascript/270653-big-trip-15/blob/2fd989f70ac5f87e9dd46777d2cadfc2145c694e/src/view/abstract.js#L25-L27) удаляется ссылка. `flatpicker` и его обработчики остаются в DOM.

См. внимательно [(частичный) вариант решения этой проблемы в демо проекте](https://github.com/htmlacademy-ecmascript/taskmanager-15/commit/20ff2e0bb9d2d7b9af3091ea3ac13c71403ba9e5#diff-d3bdc89dfe9d96f5cb9a37b5081c02458c200ae96df959504dedc17313a3a254).

2021-09-06 20:17 UTC, AlexMasterov commented on src/view/form-edit.js
> +    const destination = this._destinations.find((obj) => obj.name === name);
Не исправлено.

2021-09-06 20:19 UTC, AlexMasterov commented on src/view/form-edit.js
> +    }, false);
`}, false);`

Изменение поля стоимости продолжает приводить к полной перерисовки формы, включая пересоздания `flatpicker` (и его накопления в `DOM`). При этом ничего кроме значения в поле стоимости не изменяется.

2021-09-06 20:22 UTC, AlexMasterov commented
Пож. учти мелкие замечания в остатке и устрани утечку памяти с `flatpickr` при выполнении следующего задания.

Нужно торопиться 😃

2021-09-06 20:22 UTC, merged