Меняй-удаляй(часть1)
htmlacademy-ecmascript/270653-big-trip-15 pull request #12
Opened 2021-09-09 20:00 UTC by MikhailinNik

2021-09-10 19:56 UTC, MikhailinNik commented
Саш, помоги пожалуйста, не понимаю, почему при удалении точки маршрута, pointsModel === undefined

2021-09-10 20:55 UTC, AlexMasterov requested changes

2021-09-10 20:55 UTC, AlexMasterov commented on src/model/filter.js
> +export default class Filter extends AbstractObserver {
<details>
<summary>Filter</summary>

https://github.com/htmlacademy-ecmascript/270653-big-trip-15/blob/55c3a38be1715e291eba70a5b0f0a8d93637a510/src/model/filter.js#L4
https://github.com/htmlacademy-ecmascript/270653-big-trip-15/blob/55c3a38be1715e291eba70a5b0f0a8d93637a510/src/model/filter.js#L7
https://github.com/htmlacademy-ecmascript/270653-big-trip-15/blob/55c3a38be1715e291eba70a5b0f0a8d93637a510/src/model/filter.js#L10
https://github.com/htmlacademy-ecmascript/270653-big-trip-15/blob/55c3a38be1715e291eba70a5b0f0a8d93637a510/src/model/filter.js#L15
</details>

`Filter`._active`Filter`
**и т.п.**

[`Д 3`](https://up.htmlacademy.ru/ecmascript/15/criteries#d3)
> Название методов и свойств объектов не содержит [полное] название объектов

2021-09-10 20:55 UTC, AlexMasterov commented on src/model/points.js
> +export default class Points extends AbstractObserver {
<details>
<summary>Points</summary>

https://github.com/htmlacademy-ecmascript/270653-big-trip-15/blob/55c3a38be1715e291eba70a5b0f0a8d93637a510/src/model/points.js#L3
https://github.com/htmlacademy-ecmascript/270653-big-trip-15/blob/55c3a38be1715e291eba70a5b0f0a8d93637a510/src/model/points.js#L7
https://github.com/htmlacademy-ecmascript/270653-big-trip-15/blob/55c3a38be1715e291eba70a5b0f0a8d93637a510/src/model/points.js#L10
https://github.com/htmlacademy-ecmascript/270653-big-trip-15/blob/55c3a38be1715e291eba70a5b0f0a8d93637a510/src/model/points.js#L14
https://github.com/htmlacademy-ecmascript/270653-big-trip-15/blob/55c3a38be1715e291eba70a5b0f0a8d93637a510/src/model/points.js#L18
https://github.com/htmlacademy-ecmascript/270653-big-trip-15/blob/55c3a38be1715e291eba70a5b0f0a8d93637a510/src/model/points.js#L34
https://github.com/htmlacademy-ecmascript/270653-big-trip-15/blob/55c3a38be1715e291eba70a5b0f0a8d93637a510/src/model/points.js#L43
</details>

`Points`._`points`
**и т.п.**

[`Д 3`](https://up.htmlacademy.ru/ecmascript/15/criteries#d3)
> Название методов и свойств объектов не содержит [полное] название объектов

2021-09-10 20:55 UTC, AlexMasterov commented on src/model/points.js
> +      throw new Error('Can\'t update unexisting task');
Can\'t update unexisting `task`

🤔

2021-09-10 20:55 UTC, AlexMasterov commented on src/presenter/filter.js
> +export default class Filter {
<details>
<summary>Filter</summary>

https://github.com/htmlacademy-ecmascript/270653-big-trip-15/blob/55c3a38be1715e291eba70a5b0f0a8d93637a510/src/presenter/filter.js#L6
https://github.com/htmlacademy-ecmascript/270653-big-trip-15/blob/55c3a38be1715e291eba70a5b0f0a8d93637a510/src/presenter/filter.js#L8-L9
https://github.com/htmlacademy-ecmascript/270653-big-trip-15/blob/55c3a38be1715e291eba70a5b0f0a8d93637a510/src/presenter/filter.js#L12
https://github.com/htmlacademy-ecmascript/270653-big-trip-15/blob/55c3a38be1715e291eba70a5b0f0a8d93637a510/src/presenter/filter.js#L15
https://github.com/htmlacademy-ecmascript/270653-big-trip-15/blob/55c3a38be1715e291eba70a5b0f0a8d93637a510/src/presenter/filter.js#L41
https://github.com/htmlacademy-ecmascript/270653-big-trip-15/blob/55c3a38be1715e291eba70a5b0f0a8d93637a510/src/presenter/filter.js#L49
</details>

`Filter`._`filter`Container
**и т.п.**

[`Д 3`](https://up.htmlacademy.ru/ecmascript/15/criteries#d3)
> Название методов и свойств объектов не содержит [полное] название объектов

2021-09-10 20:55 UTC, AlexMasterov commented on src/presenter/point-list.js
>        this._renderWaypoint(point, this._destinations, this._pointTypeToOffers);
const points = this._getPoints().`slice()`

Здесь `.slice` не нужен.

2021-09-10 20:55 UTC, AlexMasterov commented on src/presenter/point-list.js
> +    this._getPoints().length === 0
Вместо этого лучше у модели для `Points` реализуй спец. метод:

```diff
- this._getPoints().length === 0
+ this._pointsModel.isEmpty()
```

2021-09-10 20:55 UTC, AlexMasterov commented on src/utils/abstract-observer.js
> +    this._observers.forEach((observer) => observer(event, payload));
`event`

Могут придраться даже с учетом затенения переменной.
Советую переименовать в `eventType` или что-то вроде.

[`Б 30`](https://up.htmlacademy.ru/ecmascript/15/criteries#b30)
> Нельзя пользоваться глобальной переменной event

2021-09-10 20:55 UTC, AlexMasterov commented on src/utils/filter.js
> +export const filter = {
<details>
<summary>utils/filter.js</summary>

https://github.com/htmlacademy-ecmascript/270653-big-trip-15/blob/55c3a38be1715e291eba70a5b0f0a8d93637a510/src/utils/filter.js#L4-L10
</details>

```diff
- export const filter = {
+ export const filterTypeToPoints = {
```

2021-09-10 20:55 UTC, AlexMasterov commented on src/utils/filter.js
> +  [FilterType.EVERYTHING]: (points) => points.filter((point) => point),
Избыточный цикл.

```diff
- [FilterType.EVERYTHING]: (points) => points.filter((point) => point),
+ [FilterType.EVERYTHING]: (points) => points.slice(),
```

2021-09-10 20:55 UTC, AlexMasterov commented on src/utils/filter.js
> +  getDifferentDate(point.dateFrom, new Date()) < 0 && getDifferentDate(point.dateTo, new Date()) > 0),
<details>
<summary>utils/filter.js</summary>

https://github.com/htmlacademy-ecmascript/270653-big-trip-15/blob/55c3a38be1715e291eba70a5b0f0a8d93637a510/src/utils/filter.js#L7-L9
</details>

Плохо: фильтрация переусложнена и работает медленно.

Объект `Date` создается заново на каждой итерации, что требует системного вызова к ОС (= производительность в опасности) и также означает его изменение (= краевые кейсы в опасности).

Вдобавок `getDifferentDate` создает объекты `dayjs`, хотя к объектам `Date` можно применять мат. операции без приведения к числу.

2021-09-10 20:55 UTC, AlexMasterov commented on src/utils/util.js
> +export const sortTimeUp = (pointA, pointB) => new Date(pointA.dateFrom) - new Date(pointB.dateFrom);
Объяснял и показывал в замечаниях и на устной консультации:
```diff
- export const sortTimeUp = (pointA, pointB) => new Date(pointA.dateFrom) - new Date(pointB.dateFrom);
+ export const sortTimeUp = (pointA, pointB) => pointA.dateFrom - pointB.dateFrom;
```

2021-09-10 20:55 UTC, AlexMasterov commented on src/view/filter.js
> +export default class Filter extends AbstractView {
<details>
<summary>Filter</summary>

https://github.com/htmlacademy-ecmascript/270653-big-trip-15/blob/55c3a38be1715e291eba70a5b0f0a8d93637a510/src/view/filter.js#L29
https://github.com/htmlacademy-ecmascript/270653-big-trip-15/blob/55c3a38be1715e291eba70a5b0f0a8d93637a510/src/view/filter.js#L34
https://github.com/htmlacademy-ecmascript/270653-big-trip-15/blob/55c3a38be1715e291eba70a5b0f0a8d93637a510/src/view/filter.js#L44
</details>

`Filter`._`filter`s
**и т.п.**

[`Д 3`](https://up.htmlacademy.ru/ecmascript/15/criteries#d3)
> Название методов и свойств объектов не содержит [полное] название объектов

2021-09-10 20:55 UTC, AlexMasterov commented on src/view/filter.js
> +debugger
`debugger`

Нужно это убрать и успокоить линтер по другим ошибкам.

[`Б 15`](https://up.htmlacademy.ru/ecmascript/15/criteries#b15)
> Код соответствует гайдлайнам

2021-09-10 20:55 UTC, AlexMasterov commented on src/view/form-edit.js
> +        <button class="event__reset-btn" type="reset">${isNewForm ? 'Cancel' : 'Delete'}</button>
`Cancel`
`Delete`

На защите проекта _могут_ придраться.

Б5

2021-09-10 20:55 UTC, AlexMasterov commented on src/view/form-edit.js
> +      .addEventListener('click', this._onDeleteClick);
.event__`reset-btn` + `click` !== this._on`Delete`Click

Д4

2021-09-10 20:55 UTC, AlexMasterov commented on src/view/form-edit.js
> +    if (this._flatpickerDateFrom && this._flatpickerDateTo) {
Желательно сделать отдельную проверку (и удаление) для каждого объекта `flatpicker` и сделать её явной:

```diff
- if (this._flatpickerDateFrom && this._flatpickerDateTo) {
+ if (this._flatpickerDateFrom !== null) {
```

2021-09-10 20:55 UTC, AlexMasterov commented on src/view/form-edit.js
> +    super.removeItem();
См. https://github.com/htmlacademy-ecmascript/270653-big-trip-15/pull/11#discussion_r702460340

remove`Item`() {
super.remove`Item`()

У род. класса `Abstract` и `Smart` нет метода с таким названием.

Нужно правильно _переопоеделить_ род. метод `removeElement`.

2021-09-10 20:55 UTC, AlexMasterov commented on src/view/form-edit.js
> +debugger
`debugger`

Б15

2021-09-10 20:55 UTC, AlexMasterov commented on src/view/form-edit.js
> +  _onDeleteClick(evt) {
[`Д 8`](https://up.htmlacademy.ru/ecmascript/15/criteries#d8)
> Методы внутри классов упорядочены

3. Основные методы класса
4. **Обработчики событий** [DOM]

2021-09-10 20:55 UTC, AlexMasterov commented on src/view/sort.js
> +    this._currentSortType = currentSortType;
`Sort`._current`Sort`Type

Д3

2021-09-10 21:09 UTC, AlexMasterov commented
> Саш, помоги пожалуйста, не понимаю, почему при удалении точки маршрута, pointsModel === undefined

Объект `Waypoint` вызывает метод другого объекта `PointList`.\_`handleViewAction` как _свой_ метод `this._changeData`, т.е. в своем контексте: в методе `PointList`.\_`handleViewAction` значение `this` заменяется на `Waypoint._pointsModel` и т.п. Поэтому при обращение к свойству `Waypoint._pointsModel` будет `undefined`, потому что у объекта `Waypoint` нет такого свойства.

Чтобы это исправить, нужно явно "привязать" контекст метода (= `this`) к объекту `PointList`, у которого это свойство `_pointsModel` имеется.

2021-09-10 21:36 UTC, AlexMasterov commented on src/presenter/point-list.js
> +        return filteredPoints.slice().sort(getPriceForSort);
<details>
<summary>presenter/point-list.js</summary>

https://github.com/htmlacademy-ecmascript/270653-big-trip-15/blob/55c3a38be1715e291eba70a5b0f0a8d93637a510/src/presenter/point-list.js#L43
</details>

`filter[this._filterType](points)` — всегда возвращает _новый_ массив.

<details>
<summary>presenter/point-list.js</summary>

https://github.com/htmlacademy-ecmascript/270653-big-trip-15/blob/55c3a38be1715e291eba70a5b0f0a8d93637a510/src/presenter/point-list.js#L49
</details>

return filteredPoints.`slice()`.sort(getPriceForSort);

Поэтому здесь не нужен `.slice`.

2021-09-10 21:44 UTC, AlexMasterov commented on src/presenter/filter.js
> +export default class Filter {
При смене фильтра выбрасывается исключение (ошибка):

```
dom.js:39 Uncaught TypeError: Cannot read properties of undefined (reading 'getElement')
    at replace (dom.js:39)
    at Filter.init (filter.js:33)
    at Filter._handleModelEvent (filter.js:38)
```

Б2

Нужно разобраться и исправить.

2021-09-10 21:45 UTC, AlexMasterov commented on src/presenter/point-list.js
Сортировка перестала работать.

Б1

Нужно разобраться и исправить.

2021-09-10 21:47 UTC, AlexMasterov commented on src/presenter/point-list.js
Если попробовать добавить точку маршрута в избранное (нажатие на кнопку "звездока"), то появляется ошибка:

```
point-list.js:113 Uncaught TypeError: Cannot read properties of undefined (reading 'updatePoint')
    at Waypoint._handleViewAction [as _changeData] (point-list.js:113)
    at Waypoint._handleFavouriteClick (waypoint.js:113)
    at Waypoint._onFavouriteButtonClick (waypoint.js:75)
```
Б2

Нужно разобраться и исправить.

2021-09-16 15:21 UTC, MikhailinNik commented
Cаш, я немного запутался, помоги пожалуйста, при добавлении новой точки маршрута у меня появляется их 3 штуки, мне надо поставить где то условие?

2021-09-16 15:42 UTC, AlexMasterov requested changes

2021-09-16 15:42 UTC, AlexMasterov commented on src/view/form-edit.js
> +  dateTo: Date.now(),
`Date.now()` возвращает _число_, а здесь нужен _объект_:

```diff
- dateFrom: Date.now(),
+ dateFrom: new Date(),
```

2021-09-16 15:42 UTC, AlexMasterov commented on src/view/form-edit.js
> +// создать в начале модуля, после import
`//`

Б18

2021-09-16 15:42 UTC, AlexMasterov commented on src/view/form-edit.js
> +  constructor(point = getBlankPoint(), destinations = [], offers = [], mode = FormMode.EDIT) {
```diff
- offers = []
+ offers = {}
```

2021-09-16 15:42 UTC, AlexMasterov commented on src/view/form-edit.js
> +
<details>
<summary>Проблема</summary>

![image](https://user-images.githubusercontent.com/700213/133641222-fb5de636-e0a8-449b-9d2f-f0406e99075c.png)

</details>

Открытою точку маршрута нельзя закрыть нажатием на "Стрелку вверх".

Нужно разобраться и исправить.

2021-09-16 15:42 UTC, AlexMasterov commented on src/view/form-edit.js
> +    const point = FormEdit.parseDateToPoint(this._data);
```diff
- const point = FormEdit.parseDateToPoint(this._data);
+ const point = FormEdit.parseDataToPoint(this._data);
```

2021-09-16 15:42 UTC, AlexMasterov commented on src/view/form-edit.js
> +    ...point // = const point = {...this._data};
Нужно раскомментировать свойства с `//` и удалить комментарии.

2021-09-16 15:42 UTC, AlexMasterov commented on src/utils/const.js
> +const listEmptyTypeToText = {
```diff
- const listEmptyTypeToText = {
+ const filterTypeToText = {
```
\+ это не константа, нужно найти другой модуль.

2021-09-16 15:42 UTC, AlexMasterov commented on src/view/form-edit.js
> +const getBlankPoint = () => ({
Нужно добавить `is_favorite`.

2021-09-16 15:42 UTC, AlexMasterov commented on src/view/form-edit.js
> +      .addEventListener('click', this._onAddButtonClick);
Компонент `view/form-edit` не должен пытаться работать с кнопкой создания новой точки маршрута, тем более через `document`. Он также не должен сам создавать новую точку маршрута.

Нужно удалить весь метод.

2021-09-16 15:45 UTC, AlexMasterov commented
> Cаш, я немного запутался, помоги пожалуйста, при добавлении новой точки маршрута у меня появляется их 3 штуки, мне надо поставить где то условие?

В этом PR нужно исправить только старые и новые замечания.

Кнопку добавление сделаешь в другом модуле. 
См. в демо проекте [пример _где_ и _как_ это следует делать](https://github.com/htmlacademy-ecmascript/taskmanager-15/blob/master/src/main.js#L35-L42).

2021-09-16 17:57 UTC, MikhailinNik commented on src/utils/const.js
> +const listEmptyTypeToText = {
не совсем понял, какой модуль?

2021-09-16 18:21 UTC, AlexMasterov commented on src/utils/const.js
> +const listEmptyTypeToText = {
> не совсем понял, какой модуль?

В новый или тот, в котором словарь непосредственно используется.

Сейчас нарушается Б14, ~Б27.

2021-09-16 19:26 UTC, AlexMasterov commented
Пожалуйста, посмотри внимательно на мелкие замечания в остатке (их около 10) и обязательно их исправь при выполнении след. задания.

2021-09-16 19:26 UTC, merged