Добавил настройку webpack resolve.alias; Разбил компоненту на две части для создания списка
htmlacademy-ecmascript/270653-big-trip-15 pull request #4
Opened 2021-07-31 21:33 UTC by MikhailinNik

2021-08-04 18:27 UTC, MikhailinNik commented
Саш, сделал всё как ты и сказал мне, сомневаюсь, что это правильно... Чего не хватает или наоборот?

2021-08-05 03:57 UTC, AlexMasterov requested changes
Для этого задания будет достаточно исправить ошибки линтера и основные замечания, а остальные оставить на консультацию.

2021-08-05 03:57 UTC, AlexMasterov commented on src/utils/util.js
> +  return `${isHours}:${isMinutes}`;
`${isHours}:`${isMinutes}

В текущем решение разряд для часов (= `00`) есть всегда, а по ТЗ его может не быть.

См. ТЗ 1.3:
> Формат продолжительности нахождения в точке маршрута зависит от длительности

> Менее часа: минуты (например, `23M`)

Нужно доработать.

2021-08-05 03:57 UTC, AlexMasterov commented on src/utils/util.js
> +  const result = getDate(dateTo) - getDate(dateFrom);
<details>
<summary>utils/util.js</summary>

https://github.com/htmlacademy-ecmascript/270653-big-trip-15/blob/9deef76ac8fa6b6a2a6001e76973a493591158c0/src/utils/util.js#L15
https://github.com/htmlacademy-ecmascript/270653-big-trip-15/blob/9deef76ac8fa6b6a2a6001e76973a493591158c0/src/utils/util.js#L18
</details>

new Date(`year`, `month`[, `day`[, hour[, minute[, second[, millisecond]]]]]);

1. Почему при вычисление длительности отбрасываются года, месяца и даже дни?

2. Если создать точки в разных месяцах, то твое решение будет работать?

> На консультации объяснял, что с объектом `Date` по спец. можно производить мат. операции без явного приведения к числу. Для вычисление продолжительности можно также использовать `dayjs`, см. [документацию](https://day.js.org/docs/ru/plugin/duration)

> Решение в целом неудачное + каскад нарушений в реализации 😟

2021-08-05 03:57 UTC, AlexMasterov commented on package.json
> +  "dependencies": {
<details>
<summary>package.json</summary>

https://github.com/htmlacademy-ecmascript/270653-big-trip-15/blob/9deef76ac8fa6b6a2a6001e76973a493591158c0/package.json#L22-L29
</details>

Пож., расскажи, в какой части лайва или задания тебя просят всё это установить? 🤔

2021-08-05 03:57 UTC, AlexMasterov commented on src/utils/const.js
> +const ZERO = '0';
<details>
<summary>utils/const.js</summary>

https://github.com/htmlacademy-ecmascript/270653-big-trip-15/blob/9deef76ac8fa6b6a2a6001e76973a493591158c0/src/utils/const.js#L8
</details>

🤔

2021-08-05 03:57 UTC, AlexMasterov commented on src/utils/const.js
> +const DATE_FORMAT = {
<details>
<summary>utils/const.js</summary>

https://github.com/htmlacademy-ecmascript/270653-big-trip-15/blob/9deef76ac8fa6b6a2a6001e76973a493591158c0/src/utils/const.js#L3-L6
</details>

`DATE_FORMAT`

Б7

Неправильной формат записи _перечисления_.

2021-08-05 03:57 UTC, AlexMasterov commented on src/utils/const.js
> +  OPTIONS,
<details>
<summary>utils/const.js</summary>

https://github.com/htmlacademy-ecmascript/270653-big-trip-15/blob/9deef76ac8fa6b6a2a6001e76973a493591158c0/src/utils/const.js#L56-L58
</details>

Б18

2021-08-05 03:57 UTC, AlexMasterov commented on src/main.js
<details>
<summary>view/form-edit.js</summary>

https://github.com/htmlacademy-ecmascript/270653-big-trip-15/blob/9deef76ac8fa6b6a2a6001e76973a493591158c0/src/view/form-edit.js#L3
</details>

<details>
<summary>view/form-offer.js</summary>

https://github.com/htmlacademy-ecmascript/270653-big-trip-15/blob/9deef76ac8fa6b6a2a6001e76973a493591158c0/src/view/form-offer.js#L1
</details>

На консультации объяснял, что все три структуры из `mock/data` нужно для `views` передавать через аргументы функции, а не импортировать в модули напрямую. Это неправильно и при реализации получения данных с сервера придётся _много_ переделывать.

2021-08-05 03:57 UTC, AlexMasterov commented on src/view/form-edit.js
> +export const createPointFormTemplate = (point) => {
<details>
<summary>Ожидание (markup/edit-point.html)</summary>

![image](https://user-images.githubusercontent.com/700213/128286816-eeeefa36-1cd0-4173-820f-25e64e90e2d7.png)

</details>

<details>
<summary>Сейчас</summary>

![image](https://user-images.githubusercontent.com/700213/128286855-306a89fa-4a08-485c-8a75-1a246dd55f10.png)

</details>

Нужно доработать отображения иконок для типов.

2021-08-05 03:57 UTC, AlexMasterov commented on src/view/form-edit.js
> +export const createPointFormTemplate = (point) => {
<details>
<summary>Сейчас</summary>

![image](https://user-images.githubusercontent.com/700213/128286969-6342dfc0-af56-4861-8fa9-6856e8780dba.png)

</details>

Нужно отображать базовую стоимость из данных.

2021-08-05 03:57 UTC, AlexMasterov commented on src/view/form-edit.js
> +export const createPointFormTemplate = (point) => {
<details>
<summary>Ожидание (markup/edit-point.html)</summary>

![image](https://user-images.githubusercontent.com/700213/128287068-57ac2e84-740a-4ebd-ab4d-d4f946607b58.png)

</details>

<details>
<summary>Сейчас</summary>

![image](https://user-images.githubusercontent.com/700213/128287181-6832cad9-10f3-473a-81cf-4edf0a170777.png)

</details>

Нужно исправить отображение кнопок для формы в режиме редактирования.

2021-08-05 03:57 UTC, AlexMasterov commented on src/view/form-edit.js
> +            ${destination === null ? '' : destination.pictures.map(({ description }) => description).join('')}
destination.`pictures.map(({ description }) => description).join('')`

В этом месте нужно использовать описание из `point.destination.description`.

2021-08-05 03:57 UTC, AlexMasterov commented on src/view/form-edit.js
> +        <section class="event__section  event__section--destination">
<details>
<summary>view/form-edit.js</summary>

https://github.com/htmlacademy-ecmascript/270653-big-trip-15/blob/9deef76ac8fa6b6a2a6001e76973a493591158c0/src/view/form-edit.js#L70-L85
</details>

См. ТЗ:
> Если информация о пункте назначения отсутствует, блок «Destination» не отображается

Нужно доработать в этом задание.

2021-08-05 03:57 UTC, AlexMasterov commented on src/view/waypoint.js
> +  return `<li class="trip-events__item">
<details>
<summary>view/waypoint.js</summary>

https://github.com/htmlacademy-ecmascript/270653-big-trip-15/blob/9deef76ac8fa6b6a2a6001e76973a493591158c0/src/view/waypoint.js#L41
https://github.com/htmlacademy-ecmascript/270653-big-trip-15/blob/9deef76ac8fa6b6a2a6001e76973a493591158c0/src/view/waypoint.js#L51
https://github.com/htmlacademy-ecmascript/270653-big-trip-15/blob/9deef76ac8fa6b6a2a6001e76973a493591158c0/src/view/waypoint.js#L55
</details>

datetime="`2019-03-18`"

На консультации объяснял, что для `datetime` достаточно использовать значение из данных в формате ISO.

2021-08-05 03:57 UTC, AlexMasterov commented on src/view/form-edit-type.js
> +export const createPointTypeTemplate = (currentType) => POINT_TYPES.map((type) => {
<details>
<summary>Ожидание (markup/edit-point.html)</summary>

![image](https://user-images.githubusercontent.com/700213/128287927-062b839b-b672-4d2f-82ad-e606cefb53c9.png)

</details>

<details>
<summary>Сейчас</summary>

![image](https://user-images.githubusercontent.com/700213/128287858-adcdc4a7-a3c3-4919-bcb4-8762d907bb79.png)

</details>

Нужно исправить разметку.

2021-08-05 03:57 UTC, AlexMasterov commented on src/view/form-offer.js
> +export const createPointOfferTemplate = () => offers.map(({ offers }) => (
Это функцию оставим на консультацию.

2021-08-05 04:49 UTC, AlexMasterov requested changes

2021-08-05 04:49 UTC, AlexMasterov commented on src/view/waypoint.js
> +      ${isType} ${destination === null ? '' : destination.description}</h3>
<details>
<summary>Сейчас</summary>

![image](https://user-images.githubusercontent.com/700213/128292471-e7651568-5106-4e47-97a3-fca094b733a9.png)
</details>

Вместо `destination.description` нужно использовать название направления:  `destination.name`.

2021-08-05 10:36 UTC, MikhailinNik commented on package.json
> +  "dependencies": {
В файле requirements.md были списки зависимостей, вот я их и установил😀 Какие то из них не нужны?

2021-08-05 10:42 UTC, AlexMasterov commented on package.json
> +  "dependencies": {
> В файле requirements.md были списки зависимостей, вот я их и установил😀

Ничего себе вас теперь балуют 😃

> Какие то из них не нужны?

Для реализации ТЗ потребуются все, что уже сейчас добавлены. Оставляй

2021-08-06 01:41 UTC, merged