Создана директория для presenter:
htmlacademy-ecmascript/270653-big-trip-15 pull request #8
Opened 2021-08-15 18:24 UTC by MikhailinNik

-создан класс презентер для отрисовки списка точки маршрута;
-добавлено новое подключение директории presenter (webpack.config.js)

2021-08-17 23:00 UTC, AlexMasterov requested changes

2021-08-18 03:31 UTC, AlexMasterov commented on src/presenter/waypoint.js
> +import FormEditView from '@view/form-edit';
<details>
<summary>view/form-edit.js</summary>

https://github.com/htmlacademy-ecmascript/270653-big-trip-15/blob/d32512a6d708fc34b598a52e72830b3726c51af3/src/view/form-edit.js#L7
</details>

Это же объект-словарь:
```diff
-  pointTypeToOffers = []
+  pointTypeToOffers = {}
```

2021-08-18 03:33 UTC, AlexMasterov commented on src/presenter/point-list.js
> +    points.length === 0
```js
_renderList() {
  this_points.length === 0
```

2021-08-18 03:33 UTC, AlexMasterov commented on src/presenter/point-list.js
> +  constructor(mainEvents) {
```diff
- constructor(mainEvents) {
+ constructor(container) {
```

2021-08-18 03:35 UTC, AlexMasterov commented on src/presenter/point-list.js
> +    points.length === 0
Можно использовать `this`:
```js
_renderListEmpty() {
  this_points.length === 0
```
> + Название функции не соответствует её действию

2021-08-18 14:34 UTC, MikhailinNik commented on src/presenter/waypoint.js
> +
я могу использовать слово handle в коллбэках для функция обработчиков? или как то  по другому можно называть, в голову ничего умного не приходит

2021-08-18 15:05 UTC, AlexMasterov commented on src/presenter/waypoint.js
> +
> я могу использовать слово handle в коллбэках для функция обработчиков?

Для именования функций-обработчиков событий _компонентов_ можешь следовать примеру демо проекта.

Главное не спутай с обработчиками событий _DOM_, которые не вызываются в коде, а только добавляются с помощью `addEventListener` в событийную систему браузера (и им же вызываются).

2021-08-18 16:37 UTC, AlexMasterov requested changes
К сожалению, нужно еще немного доработать.

2021-08-18 16:37 UTC, AlexMasterov commented on src/utils/const.js
> +const pointMode = {
`p`ointMode 

[`Б 7`](https://up.htmlacademy.ru/ecmascript/15/criteries#b7)
> Перечисления (Enum) названы английскими существительными и начинаются с прописной (заглавной) буквы

> Это режим _формы_ [`FormEdit`](https://github.com/htmlacademy-ecmascript/270653-big-trip-15/blob/3cca0475e56597a2af9cb52de7649d14e9934ea3/src/view/form-edit.js#L89), а не _точки маршрута_. Неудачное название

2021-08-18 16:37 UTC, AlexMasterov commented on src/utils/dom.js
> +const render = (container, child, place = 'afterend') => {
place = `'afterend'`

<details>
<summary>utils/dom.js</summary>

https://github.com/htmlacademy-ecmascript/270653-big-trip-15/blob/3cca0475e56597a2af9cb52de7649d14e9934ea3/src/utils/dom.js#L17-L20
</details>

Ожидалось, что будет использован `default` с некой обработкой отсутствия подходящего `case` для значения `place`, а тут что-то странное и даже опасное 🤔

Лучше убрать и вернуть, как было.

2021-08-18 16:37 UTC, AlexMasterov commented on src/view/waypoint.js
> +  setOnEditclick(callback) {
setOnEdit`c`lick

[`Б 3`](https://up.htmlacademy.ru/ecmascript/15/criteries#b3)
> Название переменных, параметров, свойств и методов начинается со строчной буквы и записываются в нотации` camelCase`

2021-08-18 16:37 UTC, AlexMasterov commented on src/utils/dom.js
<details>
<summary>utils/dom.js</summary>

https://github.com/htmlacademy-ecmascript/270653-big-trip-15/blob/3cca0475e56597a2af9cb52de7649d14e9934ea3/src/utils/dom.js#L37
</details>

`to`Item
`from`Item

На защите проекта могут придраться к таким названиями.

[`Б 4`](https://up.htmlacademy.ru/ecmascript/15/criteries#b4)
> Для названия значений используются английские существительные

2021-08-18 16:37 UTC, AlexMasterov commented on src/view/waypoint.js
>      this.getElement().querySelector('.event__rollup-btn').addEventListener('click', this._onRollUpButtonClick);
this._on`RollUp`ButtonClick

Б4

В данном случае это одно слово:

```diff
- this._onRollUpButtonClick
+ this._onRollupButtonClick
```
> Нужно исправить в другом месте, если оно есть

2021-08-18 16:37 UTC, AlexMasterov commented on src/presenter/waypoint.js
> +  }
Ожидалось, что удаление обработчика просто вложишь в метод `_replaceFormToPoint`.

Вместо этого ты создал метод-обертку с другим именем и теперь повторяется уже его вызов.

2021-08-18 16:37 UTC, AlexMasterov commented on src/presenter/waypoint.js
> +export default class Waypoint {
<details>
<summary>Waypoint</summary>

https://github.com/htmlacademy-ecmascript/270653-big-trip-15/blob/3cca0475e56597a2af9cb52de7649d14e9934ea3/src/presenter/waypoint.js#L7
https://github.com/htmlacademy-ecmascript/270653-big-trip-15/blob/3cca0475e56597a2af9cb52de7649d14e9934ea3/src/presenter/waypoint.js#L77
https://github.com/htmlacademy-ecmascript/270653-big-trip-15/blob/3cca0475e56597a2af9cb52de7649d14e9934ea3/src/presenter/waypoint.js#L83
</details>

`Waypoint`.__handle`Waypoint`Click
**и т.п.**

Д3

2021-08-18 16:37 UTC, AlexMasterov commented on src/presenter/waypoint.js
> +    this._pointComponent = new WaypointView(point);
this._`point`Component = new `Waypoint`View(point);

😃

2021-08-18 17:30 UTC, AlexMasterov commented on src/utils/dom.js
> +const replace = (place, secondElement, firstElement) => {
second`Element`

[`Д 6`](https://up.htmlacademy.ru/ecmascript/15/criteries#d6)
> Используется единый стиль именования переменных
> если есть переменные, которые хранят DOM-элемент и содержат слово Element, **то это правило работает везде**

2021-08-18 17:30 UTC, merged

2021-08-19 00:51 UTC, AlexMasterov commented on src/presenter/waypoint.js
> +import { FormEdit } from '@utils/const';
```diff
- import { FormEdit } from '@utils/const';
+ import { FormEditMode } from '@utils/const';
```