Большие перемены(ч.2):
htmlacademy-ecmascript/270653-big-trip-15 pull request #9
Opened 2021-08-19 19:24 UTC by MikhailinNik

-реализована сортировка точек маршрута по дате, времени и цене

2021-08-19 20:25 UTC, AlexMasterov requested changes

2021-08-19 20:25 UTC, AlexMasterov commented on src/view/sort.js
> +    currentType.setAttribute('checked', 'checked');
`.removeAttribute`
`.setAttribute`

[`Д 7`](https://up.htmlacademy.ru/ecmascript/15/criteries#d7)
> При использовании встроенного API, который поддерживает несколько вариантов использования, используется один способ

2021-08-19 20:25 UTC, AlexMasterov commented on src/view/sort.js
> +    const inputTypes = document.querySelectorAll('.trip-sort__input');
`document`.querySelectorAll('.trip-sort__input')

Желательно искать через `this.getElement()`.

2021-08-19 20:25 UTC, AlexMasterov commented on src/view/sort.js
> +    currentType.setAttribute('checked', 'checked');
[`Д 21`](https://up.htmlacademy.ru/ecmascript/15/criteries#d21)
> Изменения применяются точечно

2021-08-19 20:25 UTC, AlexMasterov commented on src/view/sort.js
> +    this.getElement().addEventListener('click', this._onTypeChange);
`click` !== this._onType`Change`

2021-08-19 20:25 UTC, AlexMasterov commented on src/utils/util.js
> +const sortPrice = (firstPrice, secondPrice) => secondPrice.basePrice - firstPrice.basePrice;
<details>
<summary>sortTime</summary>

https://github.com/htmlacademy-ecmascript/270653-big-trip-15/blob/8278ee78241677a4812df2e9eb010fa81650eb39/src/utils/util.js#L45-L50
</details>

<details>
<summary>sortPrice</summary>

https://github.com/htmlacademy-ecmascript/270653-big-trip-15/blob/8278ee78241677a4812df2e9eb010fa81650eb39/src/utils/util.js#L52
</details>

`sort`Time
`sort`Price

 Обе функции ничего не сортируют, а возвращают результат вычитания.

Б10

2021-08-19 20:25 UTC, AlexMasterov commented on src/utils/util.js
> +const getMilliseconds = (point) => point.dateTo - point.dateFrom;
Функция возвращает `duration`.

Б10

2021-08-19 20:25 UTC, AlexMasterov commented on src/view/sort.js
> +    <label class="trip-sort__btn" for="sort-price" data-sort-type="${SortType.PRICE}" >Price</label>
Зачем `data-sort-type`, когда уже есть `input` с такими же значениями у атрибутов `id`, `name` и `value` 🤔

2021-08-19 20:25 UTC, AlexMasterov commented on src/view/sort.js
> +  _onTypeChange(evt) {
Д8

2021-08-20 09:29 UTC, MikhailinNik commented on src/utils/util.js
> +const getMilliseconds = (point) => point.dateTo - point.dateFrom;
Правильно ли будет назвать функцию с уточнением, что длительность времени `getDurationTime`?

2021-08-20 11:45 UTC, AlexMasterov commented on src/utils/util.js
> +const getMilliseconds = (point) => point.dateTo - point.dateFrom;
> Правильно ли будет назвать функцию с уточнением, что длительность времени `getDurationTime`?

`getPointDuration`

2021-08-20 11:49 UTC, MikhailinNik commented on src/utils/util.js
> +const getMilliseconds = (point) => point.dateTo - point.dateFrom;
Понял, благодарю!

2021-08-20 12:05 UTC, AlexMasterov commented on src/utils/const.js
> +  SORT_PRICE: 'sort-price',
InputValueFor`Sort`
`SORT`_DAY
`SORT`_TIME
`SORT`_PRICE

Неправильное название для перечисление и даже ключей.

[`Б 16`](https://up.htmlacademy.ru/ecmascript/15/criteries#b16)
> Множества однотипных констант собираются в перечисления

2021-08-20 12:05 UTC, AlexMasterov commented on src/view/sort.js
> +    this.getElement().addEventListener('click', this._onTypeChange);
`click` !== this._onType`Change`

[`Д 4`](https://up.htmlacademy.ru/ecmascript/15/criteries#d4)
> Название обработчика строится следующим образом

> `on` + `(на каком элементе)` + **`что случилось`**

2021-08-20 12:06 UTC, merged